output "endpoint" {
  description = "Connection endpoint (writer endpoint for Aurora, instance endpoint for standalone RDS)"
  value       = var.use_aurora ? aws_rds_cluster.this[0].endpoint : aws_db_instance.this[0].endpoint
}

output "reader_endpoint" {
  description = "Aurora reader (load-balanced read replica) endpoint. Null for standalone RDS."
  value       = var.use_aurora ? aws_rds_cluster.this[0].reader_endpoint : null
}

output "port" {
  description = "Database port"
  value       = local.port
}

output "db_name" {
  description = "Name of the default database"
  value       = var.db_name
}

output "master_username" {
  description = "Master username"
  value       = var.master_username
}

output "master_password" {
  description = "Master password (either the one supplied via var.master_password, or the one generated by the module)"
  value       = local.master_password
  sensitive   = true
}

output "security_group_id" {
  description = "ID of the security group attached to the database"
  value       = aws_security_group.this.id
}

output "subnet_group_name" {
  description = "Name of the DB subnet group"
  value       = aws_db_subnet_group.this.name
}

output "id" {
  description = "Cluster identifier (Aurora) or instance identifier (standalone RDS)"
  value       = var.use_aurora ? aws_rds_cluster.this[0].id : aws_db_instance.this[0].id
}

output "arn" {
  description = "ARN of the cluster (Aurora) or instance (standalone RDS)"
  value       = var.use_aurora ? aws_rds_cluster.this[0].arn : aws_db_instance.this[0].arn
}
