image:
  repository: 486553676459.dkr.ecr.eu-west-1.amazonaws.com/lesson-5-ecr
  tag: 31fbb6a
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 8000

replicaCount: 2

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 6
  targetCPUUtilizationPercentage: 70

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi

config:
  SECRET_KEY: "django-insecure-change-me-in-production"
  DEBUG: "True"
  POSTGRES_HOST: "db"
  POSTGRES_PORT: "5432"
  POSTGRES_DB: "mydb"
  POSTGRES_USER: "myuser"
  POSTGRES_PASSWORD: "mypassword"
  ALLOWED_HOSTS: "*"
