image:
  repository: <ACCOUNT_ID>.dkr.ecr.eu-west-1.amazonaws.com/lesson-5-ecr
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 8000

replicaCount: 2

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 6
  targetCPUUtilizationPercentage: 70

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi

config:
  POSTGRES_HOST: "db"
  POSTGRES_PORT: "5432"
  POSTGRES_USER: "django_user"
  POSTGRES_DB: "django_db"
  POSTGRES_PASSWORD: "pass9764gd"
  DJANGO_SETTINGS_MODULE: "myproject.settings"
  DEBUG: "false"
  ALLOWED_HOSTS: "*"
